packages:
  - "packages/*"

# use when packages re-use deps and require compatible (ie. the same) versions
catalog:
  effect: ^3.17.14
  "@effect/platform": ^0.92.1
  "@effect/platform-node": ^0.98.3

