/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicLayoutRouteImport } from './routes/_public/layout'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as ApplicationWorkspaceLayoutRouteImport } from './routes/_application/$workspace/layout'
import { Route as ApplicationWorkspaceIndexRouteImport } from './routes/_application/$workspace/index'

const PublicLayoutRoute = PublicLayoutRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const ApplicationWorkspaceLayoutRoute =
  ApplicationWorkspaceLayoutRouteImport.update({
    id: '/_application/$workspace',
    path: '/$workspace',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApplicationWorkspaceIndexRoute =
  ApplicationWorkspaceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ApplicationWorkspaceLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$workspace': typeof ApplicationWorkspaceLayoutRouteWithChildren
  '/': typeof PublicIndexRoute
  '/$workspace/': typeof ApplicationWorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/$workspace': typeof ApplicationWorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicLayoutRouteWithChildren
  '/_application/$workspace': typeof ApplicationWorkspaceLayoutRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/_application/$workspace/': typeof ApplicationWorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$workspace' | '/' | '/$workspace/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$workspace'
  id:
    | '__root__'
    | '/_public'
    | '/_application/$workspace'
    | '/_public/'
    | '/_application/$workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
  ApplicationWorkspaceLayoutRoute: typeof ApplicationWorkspaceLayoutRouteWithChildren
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_application/$workspace': {
      id: '/_application/$workspace'
      path: '/$workspace'
      fullPath: '/$workspace'
      preLoaderRoute: typeof ApplicationWorkspaceLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_application/$workspace/': {
      id: '/_application/$workspace/'
      path: '/'
      fullPath: '/$workspace/'
      preLoaderRoute: typeof ApplicationWorkspaceIndexRouteImport
      parentRoute: typeof ApplicationWorkspaceLayoutRoute
    }
  }
}

interface PublicLayoutRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

interface ApplicationWorkspaceLayoutRouteChildren {
  ApplicationWorkspaceIndexRoute: typeof ApplicationWorkspaceIndexRoute
}

const ApplicationWorkspaceLayoutRouteChildren: ApplicationWorkspaceLayoutRouteChildren =
  {
    ApplicationWorkspaceIndexRoute: ApplicationWorkspaceIndexRoute,
  }

const ApplicationWorkspaceLayoutRouteWithChildren =
  ApplicationWorkspaceLayoutRoute._addFileChildren(
    ApplicationWorkspaceLayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
  ApplicationWorkspaceLayoutRoute: ApplicationWorkspaceLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
